### ISSUE TITLE
 ERROR: Got signal [signal:11(SIGSEGV),reason:128,refaddr:(nil)]. Crashing ...

### ISSUE THREAD

**Issue by nabilmamori** [k1nky/libzbxhaproxy#1]
hello, 
After installing your module I have this error Do you have a solution to solve this problem thank you

` # zabbix_agentd -V`

`zabbix_agentd (daemon) (Zabbix) 3.4.9`

`# haproxy -v`

`HA-Proxy version 1.5.18 2016/05/10`

`#  zabbix_agentd  -t  haproxy.discovery[/var/lib/haproxy/stats]`

```
zabbix_agentd [8605]: starting agent module zbxhaproxy
zabbix_agentd [8605]: DEBUG: module zbxhaproxy have discovery
zabbix_agentd [8605]: ERROR: Got signal [signal:11(SIGSEGV),reason:128,refaddr:(nil)]. Crashing ...
zabbix_agentd [8605]: ERROR: ====== Fatal information: ======
zabbix_agentd [8605]: ERROR: Program counter: 0x7fdb995a86f5
zabbix_agentd [8605]: ERROR: === Registers: ===
zabbix_agentd [8605]: ERROR: r8      =                0 =                    0 =                    0
zabbix_agentd [8605]: ERROR: r9      = 6870223a227d454d =  7525552610418181453 =  7525552610418181453
zabbix_agentd [8605]: ERROR: r10     =             ffff =                65535 =                65535
zabbix_agentd [8605]: ERROR: r11     =             c0c0 =                49344 =                49344
zabbix_agentd [8605]: ERROR: r12     =     563ef4148bd0 =       94828382948304 =       94828382948304
zabbix_agentd [8605]: ERROR: r13     =     7ffdf2a1ffd0 =      140728674156496 =      140728674156496
zabbix_agentd [8605]: ERROR: r14     =                0 =                    0 =                    0
zabbix_agentd [8605]: ERROR: r15     =                0 =                    0 =                    0
zabbix_agentd [8605]: ERROR: rdi     =     7ffdf2a1f380 =      140728674153344 =      140728674153344
zabbix_agentd [8605]: ERROR: rsi     =                e =                   14 =                   14
zabbix_agentd [8605]: ERROR: rbp     =     7ffdf2a1f5b0 =      140728674153904 =      140728674153904
zabbix_agentd [8605]: ERROR: rbx     = 3a2261746164227b =  4189017755886035579 =  4189017755886035579
zabbix_agentd [8605]: ERROR: rdx     =     7ffdf2a1f5be =      140728674153918 =      140728674153918
zabbix_agentd [8605]: ERROR: rax     = 6d706870223a227d =  7885917778345599613 =  7885917778345599613
zabbix_agentd [8605]: ERROR: rcx     =     7ffdf2a1f330 =      140728674153264 =      140728674153264
zabbix_agentd [8605]: ERROR: rsp     =     7ffdf2a1f2f0 =      140728674153200 =      140728674153200
zabbix_agentd [8605]: ERROR: rip     =     7fdb995a86f5 =      140581147412213 =      140581147412213
zabbix_agentd [8605]: ERROR: efl     =            10202 =                66050 =                66050
zabbix_agentd [8605]: ERROR: csgsfs  =   2b000000000033 =    12103423998558259 =    12103423998558259
zabbix_agentd [8605]: ERROR: err     =                0 =                    0 =                    0
zabbix_agentd [8605]: ERROR: trapno  =                d =                   13 =                   13
zabbix_agentd [8605]: ERROR: oldmask =                0 =                    0 =                    0
zabbix_agentd [8605]: ERROR: cr2     =                0 =                    0 =                    0
zabbix_agentd [8605]: ERROR: === Backtrace: ===
Segmentation fault

```

**Comment by k1nky** [comment]
@mamorinabil Hello, please tell me what OS are you using? I assume it is CentOS 6, for your convenience I have prepared [RPM](https://github.com/k1nky/libzbxhaproxy/releases/tag/RPM) -try `libzbxhaproxy-zabbix3.4-1.0-1.el6.x86_64.rpm`
I would also to know gcc version `gcc -v` and whether changes have been made to Makefile.
Thanks for you feedback

**Comment by nabilmamori** [comment]
Thank you for your reply @k1nky ,
Yes exactly I use `centos 6` , `gcc version 4.8.5 20150623`
I tried both versions (rmp), I also tried scripts with Zabbix headers.
I found the problem, it's in the Haproxy configuration.
it works well with a single block of listen :

Example:

```
......
listen srv_nginx
   server VM-1 192.168.1.199:8080 check
   server VM-2 192.168.1.222:8080 check
.....
```
```
# zabbix_agentd -t haproxy.discovery[/var/lib/haproxy/stats]

zabbix_agentd [24380]: starting agent module zbxhaproxy
zabbix_agentd [24380]: DEBUG: module zbxhaproxy have discovery
zabbix_agentd [24380]: DEBUG: module zbxhaproxy response: {"data":[{"{#PXNAME}":"srv_nginx","{#SVNAME}":"FRONTEND"},{"{#PXNAME}":"srv_nginx","{#SVNAME}":"VM-1"},{"{#PXNAME}":"srv_nginx","{#SVNAME}":"VM-2"},{"{#PXNAME}":"srv_nginx","{#SVNAME}":"BACKEND"},{"{#PXNAME}":"haproxy.stats","{#SVNAME}":"FRONTEND"},{"{#PXNAME}":"haproxy.stats","{#SVNAME}":"BACKEND"}]}
haproxy.discovery[/var/lib/haproxy/stats]     [s|{"data":[{"{#PXNAME}":"srv_nginx","{#SVNAME}":"FRONTEND"},{"{#PXNAME}":"srv_nginx","{#SVNAME}":"VM-1"},{"{#PXNAME}":"srv_nginx","{#SVNAME}":"VM-2"},{"{#PXNAME}":"srv_nginx","{#SVNAME}":"BACKEND"},{"{#PXNAME}":"haproxy.stats","{#SVNAME}":"FRONTEND"},{"{#PXNAME}":"haproxy.stats","{#SVNAME}":"BACKEND"}]}]

# zabbix_agentd -t haproxy.stat[/var/lib/haproxy/stats,srv_nginx,VM-2,status]
zabbix_agentd [25980]: starting agent module zbxhaproxy
haproxy.stat[/var/lib/haproxy/stats,srv_nginx,VM-2,status] [s|UP]

```

but when I add second block it does not work

Example:

```
....
listen srv_nginx
   server VM-1 192.168.1.199:8080 check
   server VM-2 192.168.1.222:8080 check

listen srv_apache
   server VM-1 192.168.1.199:80 check
   server VM-2 192.168.1.222:80 check
.....
```
The script only works with a single block of listen 

Thank you

**Comment by k1nky** [comment]
Hello, @mamorinabil 

I tried to reproduce the problem in test environment on AWS: 
<pre>
# cat /etc/redhat-release
CentOS release 6.10 (Final)
# uname -r
2.6.32-754.10.1.el6.x86_64
# haproxy -v
HA-Proxy version 1.5.18 2016/05/10
# zabbix_agentd -V
zabbix_agentd (daemon) (Zabbix) 3.4.9
# rpm -qi libzbxhaproxy
Name        : libzbxhaproxy                Relocations: (not relocatable)
Version     : 1.0                               Vendor: (none)
Release     : 1.el6                         Build Date: Sun 01 Dec 2019 08:08:27 PM UTC
Install Date: Tue 03 Dec 2019 06:22:40 PM UTC      Build Host: b3c5e82c754f
Group       : Unspecified                   Source RPM: libzbxhaproxy-1.0-1.el6.src.rpm
Size        : 24862                            License: GPL
Signature   : (none)
URL         : https://github.com/k1nky/libzbxhaproxy
Summary     : libzbxhaproxy for zabbix-agent version 3
</pre>
The module has been installed from project releases - [libzbxhaproxy-zabbix3.4-1.0-1.el6.x86_64.rpm](https://github.com/k1nky/libzbxhaproxy/releases/download/RPM/libzbxhaproxy-zabbix3.4-1.0-1.el6.x86_64.rpm).

There is two listen block in haproxy configuration file.
<pre>
listen srv_a
	bind *:5010
	server VM-1 127.0.0.1:80 check
	server VM-2 127.0.0.2:80 check

listen srv_b
	bind *:5020
	server VM-1 127.0.0.1:8080 check
	server VM-2 127.0.0.2:8080 check
</pre>

And then
<pre>
# zabbix_agentd -t haproxy.discovery[/var/lib/haproxy/stats]
zabbix_agentd [1530]: starting agent module zbxhaproxy
haproxy.discovery[/var/lib/haproxy/stats]     [s|{"data":[{"{#PXNAME}":"srv_a","{#SVNAME}":"FRONTEND"},{"{#PXNAME}":"srv_a","{#SVNAME}":"VM-1"},{"{#PXNAME}":"srv_a","{#SVNAME}":"VM-2"},{"{#PXNAME}":"srv_a","{#SVNAME}":"BACKEND"},{"{#PXNAME}":"srv_b","{#SVNAME}":"FRONTEND"},{"{#PXNAME}":"srv_b","{#SVNAME}":"VM-1"},{"{#PXNAME}":"srv_b","{#SVNAME}":"VM-2"},{"{#PXNAME}":"srv_b","{#SVNAME}":"BACKEND"}]}]
</pre>

Also i tried to build and install from source. I used zabbix 3.4 sources and changed `gcc_com_options` in Makefile like that:
<pre>
...
gcc_com_options = -std=gnu99 -fPIC -w -lm
...
</pre>
It works well also. My gcc version is 4.4.7, but i'm not sure there is seriously different. You can try re-build also.

Can you attach your haproxy configuration file?
