### ISSUE TITLE
syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by shailendra-singh93** [k1nky/libzbxhaproxy#4]
Hi

I am using cenos-7 for this:
1st VM ( zabbix-server )
2nd VM( zabbix-agent ) where HAProxy 2.0.7 is running.

after cloning libzbx from github : https://github.com/k1nky/libzbxhaproxy.git
cd /libzbxhaproxy
run " make zbx_include=<ZABBIX_INCLUDE>"

[root@haproxy-test2 libzbxhaproxy]# make zbx_include=<ZABBIX_INCLUDE>
-bash: syntax error near unexpected token `newline'

If I skip this and run next cmd as below:

[root@haproxy-test libzbxhaproxy]# make install
install -Z -v -m 755 ./build/libzbxhaproxy.so /usr/local/lib/libzbxhaproxy.so
install: cannot stat ‘./build/libzbxhaproxy.so’: No such file or directory
make: *** [install] Error 1
[root@haproxy-test libzbxhaproxy]#

zabbix-agent on this machine is running:
[root@haproxy-test2 libzbxhaproxy]# zabbix_agentd -V
zabbix_agentd (daemon) (Zabbix) 3.0.31
Revision 3e15255cda 27 April 2020, compilation time: Apr 27 2020 15:15:48

On zabbix-server'
[root@test-ui ~]# zabbix_server -V
zabbix_server (Zabbix) 4.0.26
Revision eb5a408168 26 October 2020, compilation time: Oct 26 2020 09:34:12

I used below ansible script to install zabbix:
https://github.com/shailendra-singh93/zabbix-ansible-centos

Please suggest how cab I make this work.
Thanks in advance.

**Comment by zacaro** [comment]
You need to replace the "variable" <ZABBIX_INCLUDE> with the folder containing the Zabbix sources that you should have downloaded before. 

For example, this is my run.

```
# make zbx_include=/opt/zabbix-4.0.29/include
mkdir -p ./build
if test ! -f /opt/zabbix-4.0.29/includeconfig.h; then echo "" > /opt/zabbix-4.0.29/includeconfig.h; fi
gcc -std=gnu11 -fPIC -Wall -lm -c src/hash_table.c -o ./build/hash_table.o
gcc -std=gnu11 -fPIC -Wall -lm -c src/prime.c -o ./build/prime.o
gcc -std=gnu11 -fPIC -Wall -lm -c src/haproxy_stat.c -o ./build/haproxy_stat.o
gcc -std=gnu11 -fPIC -Wall -lm -c src/haproxy_servers.c -o ./build/haproxy_servers.o
gcc -std=gnu11 -fPIC -Wall -lm -c src/zbxhaproxy.c -o ./build/zbxhaproxy.o -I/opt/zabbix-agent/include
gcc -std=gnu11 -fPIC -Wall -lm -shared -o ./build/libzbxhaproxy.so ./build/hash_table.o ./build/prime.o ./build/haproxy_stat.o ./build/haproxy_servers.o ./build/zbxhaproxy.o
```

After that, you can continue with the installation.
